app:
  debug: true
  allowed_hosts:
    - localhost
    - 127.0.0.1
    - 34.154.100.33
    - weightlessly-tres-dagmar.ngrok-free.dev
  docs:
    /docs/swagger.html
  mkdocs:
    /docs/index.html

directories:
  controllers: /app/routes
  middlewares: /app/middlewares
  static: static
  
database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  socket: /run/mysqld/mysqld.sock
  name: tps
  user: root
  password: ""
  charset: utf8mb4
