jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server   # ← aggiungi questa riga
    steps:
      - name: SSH e git pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html
            sudo git pull
