name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: server
    steps:
      - name: SSH e git pull
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            cd /var/www/html
            git pull
